<a href="https://colab.research.google.com/github/larislima11/exercicio_etl/blob/main/EXEMPLO_ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd

df_csv = pd.read_csv('dados.csv')
print("Dados do CSV:")
print(df_csv)

df_xlsx = pd.read_excel('dados.xlsx', engine='openpyxl')
print("Dados do XLSX:")
print(df_xlsx)

# Transformação dos dados: Calcular o valor total de vendas para cada item
df_csv['Valor Total'] = df_csv['venda'] * df_csv['preço']
print("Dados transformados do CSV:")
print(df_csv)

#Visuzalização dos dados transformados
df_csv['Valor Total'] = df_csv['venda'] * df_csv['preço']
df_csv.head()
print("Dados transformados do CSV:")
print(df_csv)

df_xlsx['Valor Total'] = df_xlsx['venda'] * df_xlsx['preço']
df_xlsx.head()
print("Dados transformados do XLSX:")
print(df_xlsx)

# Carregamento dos dados transformados para um arquivo CSV
df_csv.to_csv('dados_transformados.csv', index=False)

# Carregamento dos dados transformados para um arquivo XLSX
df_xlsx.to_excel('dados_transformados.xlsx', index=False)

# Apresentar os dados carregados dos arquivos CSV
print("Dados carregados do CSV:")
print(df_csv)

# Apresentar os dados carregados dos arquivos XLSX
print("Dados carregados do XLSX:")
print(df_xlsx)

import sqlite3
conn = sqlite3.connect ('dados_transformados.db')

# Carregar os dados transformados para tabelas SQL
df_csv.to_sql('dados_csv', conn, if_exists='replace', index=False)
df_xlsx.to_sql('dados_xlsx', conn, if_exists='replace', index=False)

#Apresentar os dados das tabelas SQL
df_sql_csv = pd.read_sql_query('SELECT * FROM dados_csv', conn) # Use read_sql_query to read from the database
df_xlsx = pd.read_sql_query('SELECT * FROM dados_xlsx', conn) # Use read_sql_query to read from the database

print("Dados carregados do CSV (SQL):")
print(df_sql_csv)

print("Dados carregados do XLSX (SQL):")
print(df_xlsx)

conn.close()

import sqlite3

# Conexão Banco de dados
conn = sqlite3.connect('dados_transformados.db')

#cursor consultas sql
cursor = conn.cursor()

# Consulta sql para obter dados da tabela vendas_filial1_transformadas
cursor.execute('SELECT * FROM dados_csv')
dados_csv = cursor.fetchall()

# Consulta sql para obter dados da tabela vendas_filial2_transformadas
cursor.execute('SELECT * FROM dados_xlsx')
dados_xlsx = cursor.fetchall()

print("Dados transformados da tabela dados_csv:")
for linha in dados_csv:
    print(linha)

print("Dados transformados da tabela dados_xlsx:")
for linha in dados_xlsx:
    print(linha)

cursor.close()
conn.close()

Dados do CSV:
   id                      nome  venda  preço
0  41             Impressora HP     25   2500
1  42  Notebook Lenovo ThinkPad     30   5000
2  43      Smartphone iPhone 15     45   6500
3  44           Monitor Dell 27     15    689
4  45         Mouse Razer Viper     35    800
Dados do XLSX:
    id                      nome  venda   preço
0   NaN                      NaN    NaN     NaN
1  31.0       SSD Kingston 512GB   25.0  2500.0
2  32.0  Headset Sony WH-1000XM4   30.0  3000.0
3  33.0            Playstation 5   45.0  4500.0
4  34.0            Xbox Series X   20.0  3400.0
5  35.0          Nintendo Switch   33.0  5500.0
Dados transformados do CSV:
   id                      nome  venda  preço  Valor Total
0  41             Impressora HP     25   2500        62500
1  42  Notebook Lenovo ThinkPad     30   5000       150000
2  43      Smartphone iPhone 15     45   6500       292500
3  44           Monitor Dell 27     15    689        10335
4  45         Mouse Razer Viper     35    800        28000
Dados transformados do CSV:
   id                      nome  venda  preço  Valor Total
0  41             Impressora HP     25   2500        62500
1  42  Notebook Lenovo ThinkPad     30   5000       150000
2  43      Smartphone iPhone 15     45   6500       292500
3  44           Monitor Dell 27     15    689        10335
4  45         Mouse Razer Viper     35    800        28000
Dados transformados do XLSX:
    id                      nome  venda   preço  Valor Total
0   NaN                      NaN    NaN     NaN          NaN
1  31.0       SSD Kingston 512GB   25.0  2500.0      62500.0
2  32.0  Headset Sony WH-1000XM4   30.0  3000.0      90000.0
3  33.0            Playstation 5   45.0  4500.0     202500.0
4  34.0            Xbox Series X   20.0  3400.0      68000.0
5  35.0          Nintendo Switch   33.0  5500.0     181500.0
Dados carregados do CSV:
   id                      nome  venda  preço  Valor Total
0  41             Impressora HP     25   2500        62500
1  42  Notebook Lenovo ThinkPad     30   5000       150000
2  43      Smartphone iPhone 15     45   6500       292500
3  44           Monitor Dell 27     15    689        10335
4  45         Mouse Razer Viper     35    800        28000
Dados carregados do XLSX:
    id                      nome  venda   preço  Valor Total
0   NaN                      NaN    NaN     NaN          NaN
1  31.0       SSD Kingston 512GB   25.0  2500.0      62500.0
2  32.0  Headset Sony WH-1000XM4   30.0  3000.0      90000.0
3  33.0            Playstation 5   45.0  4500.0     202500.0
4  34.0            Xbox Series X   20.0  3400.0      68000.0
5  35.0          Nintendo Switch   33.0  5500.0     181500.0
Dados carregados do CSV (SQL):
   id                      nome  venda  preço  Valor Total
0  41             Impressora HP     25   2500        62500
1  42  Notebook Lenovo ThinkPad     30   5000       150000
2  43      Smartphone iPhone 15     45   6500       292500
3  44           Monitor Dell 27     15    689        10335
4  45         Mouse Razer Viper     35    800        28000
Dados carregados do XLSX (SQL):
    id                      nome  venda   preço  Valor Total
0   NaN                     None    NaN     NaN          NaN
1  31.0       SSD Kingston 512GB   25.0  2500.0      62500.0
2  32.0  Headset Sony WH-1000XM4   30.0  3000.0      90000.0
3  33.0            Playstation 5   45.0  4500.0     202500.0
4  34.0            Xbox Series X   20.0  3400.0      68000.0
5  35.0          Nintendo Switch   33.0  5500.0     181500.0
Dados transformados da tabela dados_csv:
(41, 'Impressora HP', 25, 2500, 62500)
(42, 'Notebook Lenovo ThinkPad', 30, 5000, 150000)
(43, 'Smartphone iPhone 15', 45, 6500, 292500)
(44, ' Monitor Dell 27', 15, 689, 10335)
(45, ' Mouse Razer Viper', 35, 800, 28000)
Dados transformados da tabela dados_xlsx:
(None, None, None, None, None)
(31.0, 'SSD Kingston 512GB', 25.0, 2500.0, 62500.0)
(32.0, 'Headset Sony WH-1000XM4', 30.0, 3000.0, 90000.0)
(33.0, 'Playstation 5', 45.0, 4500.0, 202500.0)
(34.0, 'Xbox Series X', 20.0, 3400.0, 68000.0)
(35.0, 'Nintendo Switch', 33.0, 5500.0, 181500.0)

# Vantagens Obtidas no Processo de ETL (Extração, Transformação e Carregamento)

Automação e Eficiência:
O processo de ETL automatiza a coleta e transformação de dados de diferentes fontes, garantindo que a análise possa ser feita de forma rápida e precisa. Isso economiza tempo em relação ao processamento manual de dados.

Consolidação de Dados:
O ETL permite consolidar dados de diferentes formatos e fontes (como arquivos CSV, XLSX ou bancos de dados) em um único formato, proporcionando uma visão unificada e consistente dos dados.

Melhoria na Qualidade dos Dados:
Durante o processo de transformação, é possível realizar limpezas e ajustes nos dados (como calcular valores, filtrar colunas irrelevantes ou tratar valores ausentes), garantindo que os dados finais estejam prontos para análise sem inconsistências.

Integração com Sistemas de Banco de Dados:
O processo de carregamento final, como feito no SQLite, armazena os dados de forma organizada e eficiente, permitindo consultas rápidas e melhor gestão de grandes volumes de dados.

# O que é o SQLite?
SQLite é um sistema de gerenciamento de banco de dados relacional que não requer um servidor de banco de dados dedicado. Ao contrário de outros bancos de dados, como MySQL ou PostgreSQL, o SQLite é "embutido" em aplicativos e armazena todos os dados em um único arquivo, o que o torna extremamente leve e fácil de implementar.

# Vantagens de Utilizar o SQLite no Processo Apresentado

Simples e Leve:
O SQLite é fácil de usar e não requer um servidor de banco de dados separado. Isso torna seu uso ideal para projetos pequenos ou quando se quer testar ou prototipar algo rapidamente.

Banco de Dados Local:
Todos os dados são armazenados em um único arquivo no sistema, facilitando o transporte e a cópia do banco de dados. Esse formato é ideal para aplicações locais ou projetos onde a portabilidade é necessária.

Velocidade e Desempenho:
Para datasets pequenos e médios, o SQLite oferece um desempenho muito bom, especialmente em processos de leitura. É bastante rápido para aplicações que não exigem muitos acessos simultâneos ou volumes muito grandes de dados.

Zero Configuração:
Ao contrário de outros bancos de dados que requerem configuração e manutenção de servidores, o SQLite está pronto para uso sem a necessidade de configuração adicional.